spring:
  datasource:
    url: jdbc:mysql://39.98.186.143:3306/bank_server?characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: deepchain@20190115
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 10
    minIdle: 10
    maxActive: 100
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
#        instance-id: bank-9050
  redis:
    database: 0
    host: 39.98.186.143
    port: 6379
    jedis:
      pool:
        min-idle: 10
        max-idle: 50
        max-active: 200
        #max-wait: 3000
    password: 0b94b295921f3fc7070ef13cfced72a9

fdfs:
  so-timeout: 1500
  connect-timeout: 600
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 39.100.144.0:22122

saveFilePath: C:\Users\root\Desktop\bank_server\file\
attestationFilePath: C:\Users\root\Desktop\bank_server\file\
templatePath: C:\Users\root\Desktop\bank_server\templates\
signPath: C:\Users\root\Desktop\bank_server\signseal\bjzx\
ksPassword: cfca1234
login.userName: icbc
login.password: zxgzc

#手写签名是被相关配置
face.api.key: sadaf
face.api.secret: sadaf
hanvon.key: asdfa
hanvon.type: asdfa
xunfei.url: asdfa

deepsecPlatformUrl: http://localhost:9020/deepsecPlatform/
icbcNotaryCodeUrl: http://192.168.10.31:8059/globalid/get/1/1
deepsecBaseUrl: http://localhost:9528/base/
deepsecMessage: http://localhost:8065/

#邮件推送接口地址
push_url: http://15.0.32.216:16501
push_service: A0672N003
push_trade: A0672N003

